name: 'aws-route53-records'
description: 'GitHub Action for AWS Route53 Records Sets'
author: renatodans

inputs:
  hostedZoneId:
    required: true
    description: 'Route 53 Hosted Zone Id'  
  recordName:
    required: true
    description: 'Record name of resource'
  recordType:
    required: true
    description: 'Record type of resource - (A, CNAME, TXT...)'
    default: 'A'
  useAlias:
    required: true
    description: 'Use alias to choise AWS endpoints - (API GTW, ALB, NLB...)'
    default: 'true'
  resourceValue:
    required: true
    description: 'Record target - (Domain, IP or alias)'
    

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'upload-cloud'
  color: 'gray-dark'